---
# Common settings for all Pis
registry: "192.168.50.46:5000"
tailscale_auth_key: "{{ lookup('env', 'TAILSCALE_AUTH_KEY') }}"
tailscale_exit_node: "100.90.165.127"

mqtt_server: "192.168.50.24"
mqtt_port: 1883

# Docker compose project directory on the Pi
compose_dir: /opt/vtms
