---
hotspot_ssid: "{{ lookup('env', 'HOTSPOT_SSID') | default('vtms', true) }}"
hotspot_password: "{{ lookup('env', 'HOTSPOT_PASSWORD') }}"
hotspot_band: "bg"
hotspot_channel: 6
# NetworkManager hotspot subnet (default 10.42.0.0/24)
hotspot_subnet: "10.42.0.0/24"
